// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Defines values for FieldType.
const (
	Boolean FieldType = "boolean"
	Double  FieldType = "double"
	Keyword FieldType = "keyword"
	Long    FieldType = "long"
	Text    FieldType = "text"
)

// Valid indicates whether the value is a known member of the FieldType enum.
func (e FieldType) Valid() bool {
	switch e {
	case Boolean:
		return true
	case Double:
		return true
	case Keyword:
		return true
	case Long:
		return true
	case Text:
		return true
	default:
		return false
	}
}

// AcknowledgedResponse defines model for AcknowledgedResponse.
type AcknowledgedResponse struct {
	Acknowledged bool `json:"acknowledged"`
}

// BulkItemResponse defines model for BulkItemResponse.
type BulkItemResponse map[string]BulkItemResult

// BulkItemResult defines model for BulkItemResult.
type BulkItemResult struct {
	UnderscoreId    string       `json:"_id"`
	UnderscoreIndex string       `json:"_index"`
	Error           *ErrorDetail `json:"error,omitempty"`
	Status          int          `json:"status"`
}

// BulkResponse defines model for BulkResponse.
type BulkResponse struct {
	Errors bool               `json:"errors"`
	Items  []BulkItemResponse `json:"items"`
	Took   int                `json:"took"`
}

// CreateIndexRequest defines model for CreateIndexRequest.
type CreateIndexRequest struct {
	Mappings *Mappings `json:"mappings,omitempty"`
	Settings *Settings `json:"settings,omitempty"`
}

// CreateIndexResponse defines model for CreateIndexResponse.
type CreateIndexResponse struct {
	Acknowledged bool   `json:"acknowledged"`
	Index        string `json:"index"`
}

// DeleteDocumentResponse defines model for DeleteDocumentResponse.
type DeleteDocumentResponse struct {
	UnderscoreId    string `json:"_id"`
	UnderscoreIndex string `json:"_index"`
	Result          string `json:"result"`
}

// DocumentBody defines model for DocumentBody.
type DocumentBody map[string]interface{}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	Reason string `json:"reason"`
	Type   string `json:"type"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error  ErrorDetail `json:"error"`
	Status int         `json:"status"`
}

// FieldType defines model for FieldType.
type FieldType string

// GetDocumentResponse defines model for GetDocumentResponse.
type GetDocumentResponse struct {
	UnderscoreId     string                  `json:"_id"`
	UnderscoreIndex  string                  `json:"_index"`
	UnderscoreSource *map[string]interface{} `json:"_source,omitempty"`
	Found            bool                    `json:"found"`
}

// GetIndexResponse defines model for GetIndexResponse.
type GetIndexResponse map[string]IndexMetadata

// IndexDocumentResponse defines model for IndexDocumentResponse.
type IndexDocumentResponse struct {
	UnderscoreId    string `json:"_id"`
	UnderscoreIndex string `json:"_index"`
	Result          string `json:"result"`
}

// IndexMetadata defines model for IndexMetadata.
type IndexMetadata struct {
	Mappings *Mappings `json:"mappings,omitempty"`
	Settings *Settings `json:"settings,omitempty"`
}

// Mappings defines model for Mappings.
type Mappings struct {
	Properties *Properties `json:"properties,omitempty"`
}

// Properties defines model for Properties.
type Properties map[string]PropertyDefinition

// PropertyDefinition defines model for PropertyDefinition.
type PropertyDefinition struct {
	Analyzer *string   `json:"analyzer,omitempty"`
	Type     FieldType `json:"type"`
}

// RefreshResponse defines model for RefreshResponse.
type RefreshResponse struct {
	UnderscoreShards ShardStats `json:"_shards"`
}

// SearchHit defines model for SearchHit.
type SearchHit struct {
	UnderscoreId     string                  `json:"_id"`
	UnderscoreIndex  string                  `json:"_index"`
	UnderscoreScore  float32                 `json:"_score"`
	UnderscoreSource *map[string]interface{} `json:"_source,omitempty"`
}

// SearchHits defines model for SearchHits.
type SearchHits struct {
	Hits     []SearchHit `json:"hits"`
	MaxScore *float32    `json:"max_score,omitempty"`
	Total    SearchTotal `json:"total"`
}

// SearchRequest defines model for SearchRequest.
type SearchRequest struct {
	Query *map[string]interface{} `json:"query,omitempty"`
	Size  *int                    `json:"size,omitempty"`
}

// SearchResponse defines model for SearchResponse.
type SearchResponse struct {
	Hits SearchHits `json:"hits"`
	Took int        `json:"took"`
}

// SearchTotal defines model for SearchTotal.
type SearchTotal struct {
	Relation string `json:"relation"`
	Value    int    `json:"value"`
}

// Settings defines model for Settings.
type Settings struct {
	NumberOfReplicas *int `json:"number_of_replicas,omitempty"`
	NumberOfShards   *int `json:"number_of_shards,omitempty"`
}

// ShardStats defines model for ShardStats.
type ShardStats struct {
	Failed     int `json:"failed"`
	Successful int `json:"successful"`
	Total      int `json:"total"`
}

// DocId defines model for DocId.
type DocId = string

// IndexName defines model for IndexName.
type IndexName = string

// SizeParam defines model for SizeParam.
type SizeParam = int

// SearchGetParams defines parameters for SearchGet.
type SearchGetParams struct {
	Size *SizeParam `form:"size,omitempty" json:"size,omitempty"`
}

// SearchPostParams defines parameters for SearchPost.
type SearchPostParams struct {
	Size *SizeParam `form:"size,omitempty" json:"size,omitempty"`
}

// CreateIndexJSONRequestBody defines body for CreateIndex for application/json ContentType.
type CreateIndexJSONRequestBody = CreateIndexRequest

// IndexDocumentPostJSONRequestBody defines body for IndexDocumentPost for application/json ContentType.
type IndexDocumentPostJSONRequestBody = DocumentBody

// IndexDocumentPutJSONRequestBody defines body for IndexDocumentPut for application/json ContentType.
type IndexDocumentPutJSONRequestBody = DocumentBody

// SearchGetJSONRequestBody defines body for SearchGet for application/json ContentType.
type SearchGetJSONRequestBody = SearchRequest

// SearchPostJSONRequestBody defines body for SearchPost for application/json ContentType.
type SearchPostJSONRequestBody = SearchRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Bulk operations
	// (POST /_bulk)
	Bulk(w http.ResponseWriter, r *http.Request)
	// Delete an index
	// (DELETE /{index})
	DeleteIndex(w http.ResponseWriter, r *http.Request, index IndexName)
	// Get index metadata
	// (GET /{index})
	GetIndex(w http.ResponseWriter, r *http.Request, index IndexName)
	// Create an index
	// (PUT /{index})
	CreateIndex(w http.ResponseWriter, r *http.Request, index IndexName)
	// Bulk operations with index scope
	// (POST /{index}/_bulk)
	BulkWithIndex(w http.ResponseWriter, r *http.Request, index IndexName)
	// Delete a document
	// (DELETE /{index}/_doc/{id})
	DeleteDocument(w http.ResponseWriter, r *http.Request, index IndexName, id DocId)
	// Get a document
	// (GET /{index}/_doc/{id})
	GetDocument(w http.ResponseWriter, r *http.Request, index IndexName, id DocId)
	// Index a document (POST)
	// (POST /{index}/_doc/{id})
	IndexDocumentPost(w http.ResponseWriter, r *http.Request, index IndexName, id DocId)
	// Index a document (PUT)
	// (PUT /{index}/_doc/{id})
	IndexDocumentPut(w http.ResponseWriter, r *http.Request, index IndexName, id DocId)
	// Refresh an index
	// (POST /{index}/_refresh)
	Refresh(w http.ResponseWriter, r *http.Request, index IndexName)
	// Search documents (GET)
	// (GET /{index}/_search)
	SearchGet(w http.ResponseWriter, r *http.Request, index IndexName, params SearchGetParams)
	// Search documents (POST)
	// (POST /{index}/_search)
	SearchPost(w http.ResponseWriter, r *http.Request, index IndexName, params SearchPostParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Bulk operations
// (POST /_bulk)
func (_ Unimplemented) Bulk(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete an index
// (DELETE /{index})
func (_ Unimplemented) DeleteIndex(w http.ResponseWriter, r *http.Request, index IndexName) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get index metadata
// (GET /{index})
func (_ Unimplemented) GetIndex(w http.ResponseWriter, r *http.Request, index IndexName) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create an index
// (PUT /{index})
func (_ Unimplemented) CreateIndex(w http.ResponseWriter, r *http.Request, index IndexName) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Bulk operations with index scope
// (POST /{index}/_bulk)
func (_ Unimplemented) BulkWithIndex(w http.ResponseWriter, r *http.Request, index IndexName) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a document
// (DELETE /{index}/_doc/{id})
func (_ Unimplemented) DeleteDocument(w http.ResponseWriter, r *http.Request, index IndexName, id DocId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a document
// (GET /{index}/_doc/{id})
func (_ Unimplemented) GetDocument(w http.ResponseWriter, r *http.Request, index IndexName, id DocId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Index a document (POST)
// (POST /{index}/_doc/{id})
func (_ Unimplemented) IndexDocumentPost(w http.ResponseWriter, r *http.Request, index IndexName, id DocId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Index a document (PUT)
// (PUT /{index}/_doc/{id})
func (_ Unimplemented) IndexDocumentPut(w http.ResponseWriter, r *http.Request, index IndexName, id DocId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Refresh an index
// (POST /{index}/_refresh)
func (_ Unimplemented) Refresh(w http.ResponseWriter, r *http.Request, index IndexName) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Search documents (GET)
// (GET /{index}/_search)
func (_ Unimplemented) SearchGet(w http.ResponseWriter, r *http.Request, index IndexName, params SearchGetParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Search documents (POST)
// (POST /{index}/_search)
func (_ Unimplemented) SearchPost(w http.ResponseWriter, r *http.Request, index IndexName, params SearchPostParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Bulk operation middleware
func (siw *ServerInterfaceWrapper) Bulk(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Bulk(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteIndex operation middleware
func (siw *ServerInterfaceWrapper) DeleteIndex(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "index" -------------
	var index IndexName

	err = runtime.BindStyledParameterWithOptions("simple", "index", chi.URLParam(r, "index"), &index, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "index", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteIndex(w, r, index)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetIndex operation middleware
func (siw *ServerInterfaceWrapper) GetIndex(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "index" -------------
	var index IndexName

	err = runtime.BindStyledParameterWithOptions("simple", "index", chi.URLParam(r, "index"), &index, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "index", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetIndex(w, r, index)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateIndex operation middleware
func (siw *ServerInterfaceWrapper) CreateIndex(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "index" -------------
	var index IndexName

	err = runtime.BindStyledParameterWithOptions("simple", "index", chi.URLParam(r, "index"), &index, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "index", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateIndex(w, r, index)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BulkWithIndex operation middleware
func (siw *ServerInterfaceWrapper) BulkWithIndex(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "index" -------------
	var index IndexName

	err = runtime.BindStyledParameterWithOptions("simple", "index", chi.URLParam(r, "index"), &index, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "index", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BulkWithIndex(w, r, index)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteDocument operation middleware
func (siw *ServerInterfaceWrapper) DeleteDocument(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "index" -------------
	var index IndexName

	err = runtime.BindStyledParameterWithOptions("simple", "index", chi.URLParam(r, "index"), &index, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "index", Err: err})
		return
	}

	// ------------- Path parameter "id" -------------
	var id DocId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteDocument(w, r, index, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDocument operation middleware
func (siw *ServerInterfaceWrapper) GetDocument(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "index" -------------
	var index IndexName

	err = runtime.BindStyledParameterWithOptions("simple", "index", chi.URLParam(r, "index"), &index, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "index", Err: err})
		return
	}

	// ------------- Path parameter "id" -------------
	var id DocId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDocument(w, r, index, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// IndexDocumentPost operation middleware
func (siw *ServerInterfaceWrapper) IndexDocumentPost(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "index" -------------
	var index IndexName

	err = runtime.BindStyledParameterWithOptions("simple", "index", chi.URLParam(r, "index"), &index, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "index", Err: err})
		return
	}

	// ------------- Path parameter "id" -------------
	var id DocId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.IndexDocumentPost(w, r, index, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// IndexDocumentPut operation middleware
func (siw *ServerInterfaceWrapper) IndexDocumentPut(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "index" -------------
	var index IndexName

	err = runtime.BindStyledParameterWithOptions("simple", "index", chi.URLParam(r, "index"), &index, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "index", Err: err})
		return
	}

	// ------------- Path parameter "id" -------------
	var id DocId

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.IndexDocumentPut(w, r, index, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Refresh operation middleware
func (siw *ServerInterfaceWrapper) Refresh(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "index" -------------
	var index IndexName

	err = runtime.BindStyledParameterWithOptions("simple", "index", chi.URLParam(r, "index"), &index, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "index", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Refresh(w, r, index)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchGet operation middleware
func (siw *ServerInterfaceWrapper) SearchGet(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "index" -------------
	var index IndexName

	err = runtime.BindStyledParameterWithOptions("simple", "index", chi.URLParam(r, "index"), &index, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "index", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchGetParams

	// ------------- Optional query parameter "size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "size", r.URL.Query(), &params.Size, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "size", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchGet(w, r, index, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchPost operation middleware
func (siw *ServerInterfaceWrapper) SearchPost(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "index" -------------
	var index IndexName

	err = runtime.BindStyledParameterWithOptions("simple", "index", chi.URLParam(r, "index"), &index, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "index", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchPostParams

	// ------------- Optional query parameter "size" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "size", r.URL.Query(), &params.Size, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "size", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchPost(w, r, index, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/_bulk", wrapper.Bulk)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/{index}", wrapper.DeleteIndex)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/{index}", wrapper.GetIndex)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/{index}", wrapper.CreateIndex)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/{index}/_bulk", wrapper.BulkWithIndex)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/{index}/_doc/{id}", wrapper.DeleteDocument)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/{index}/_doc/{id}", wrapper.GetDocument)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/{index}/_doc/{id}", wrapper.IndexDocumentPost)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/{index}/_doc/{id}", wrapper.IndexDocumentPut)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/{index}/_refresh", wrapper.Refresh)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/{index}/_search", wrapper.SearchGet)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/{index}/_search", wrapper.SearchPost)
	})

	return r
}

type BulkRequestObject struct {
	Body io.Reader
}

type BulkResponseObject interface {
	VisitBulkResponse(w http.ResponseWriter) error
}

type Bulk200JSONResponse BulkResponse

func (response Bulk200JSONResponse) VisitBulkResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Bulk400JSONResponse ErrorResponse

func (response Bulk400JSONResponse) VisitBulkResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeleteIndexRequestObject struct {
	Index IndexName `json:"index"`
}

type DeleteIndexResponseObject interface {
	VisitDeleteIndexResponse(w http.ResponseWriter) error
}

type DeleteIndex200JSONResponse AcknowledgedResponse

func (response DeleteIndex200JSONResponse) VisitDeleteIndexResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteIndex404JSONResponse ErrorResponse

func (response DeleteIndex404JSONResponse) VisitDeleteIndexResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetIndexRequestObject struct {
	Index IndexName `json:"index"`
}

type GetIndexResponseObject interface {
	VisitGetIndexResponse(w http.ResponseWriter) error
}

type GetIndex200JSONResponse GetIndexResponse

func (response GetIndex200JSONResponse) VisitGetIndexResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetIndex404JSONResponse ErrorResponse

func (response GetIndex404JSONResponse) VisitGetIndexResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CreateIndexRequestObject struct {
	Index IndexName `json:"index"`
	Body  *CreateIndexJSONRequestBody
}

type CreateIndexResponseObject interface {
	VisitCreateIndexResponse(w http.ResponseWriter) error
}

type CreateIndex200JSONResponse CreateIndexResponse

func (response CreateIndex200JSONResponse) VisitCreateIndexResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CreateIndex400JSONResponse ErrorResponse

func (response CreateIndex400JSONResponse) VisitCreateIndexResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type BulkWithIndexRequestObject struct {
	Index IndexName `json:"index"`
	Body  io.Reader
}

type BulkWithIndexResponseObject interface {
	VisitBulkWithIndexResponse(w http.ResponseWriter) error
}

type BulkWithIndex200JSONResponse BulkResponse

func (response BulkWithIndex200JSONResponse) VisitBulkWithIndexResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type BulkWithIndex400JSONResponse ErrorResponse

func (response BulkWithIndex400JSONResponse) VisitBulkWithIndexResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeleteDocumentRequestObject struct {
	Index IndexName `json:"index"`
	Id    DocId     `json:"id"`
}

type DeleteDocumentResponseObject interface {
	VisitDeleteDocumentResponse(w http.ResponseWriter) error
}

type DeleteDocument200JSONResponse DeleteDocumentResponse

func (response DeleteDocument200JSONResponse) VisitDeleteDocumentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteDocument404JSONResponse DeleteDocumentResponse

func (response DeleteDocument404JSONResponse) VisitDeleteDocumentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetDocumentRequestObject struct {
	Index IndexName `json:"index"`
	Id    DocId     `json:"id"`
}

type GetDocumentResponseObject interface {
	VisitGetDocumentResponse(w http.ResponseWriter) error
}

type GetDocument200JSONResponse GetDocumentResponse

func (response GetDocument200JSONResponse) VisitGetDocumentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDocument404JSONResponse GetDocumentResponse

func (response GetDocument404JSONResponse) VisitGetDocumentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type IndexDocumentPostRequestObject struct {
	Index IndexName `json:"index"`
	Id    DocId     `json:"id"`
	Body  *IndexDocumentPostJSONRequestBody
}

type IndexDocumentPostResponseObject interface {
	VisitIndexDocumentPostResponse(w http.ResponseWriter) error
}

type IndexDocumentPost201JSONResponse IndexDocumentResponse

func (response IndexDocumentPost201JSONResponse) VisitIndexDocumentPostResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type IndexDocumentPost400JSONResponse ErrorResponse

func (response IndexDocumentPost400JSONResponse) VisitIndexDocumentPostResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type IndexDocumentPost404JSONResponse ErrorResponse

func (response IndexDocumentPost404JSONResponse) VisitIndexDocumentPostResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type IndexDocumentPutRequestObject struct {
	Index IndexName `json:"index"`
	Id    DocId     `json:"id"`
	Body  *IndexDocumentPutJSONRequestBody
}

type IndexDocumentPutResponseObject interface {
	VisitIndexDocumentPutResponse(w http.ResponseWriter) error
}

type IndexDocumentPut201JSONResponse IndexDocumentResponse

func (response IndexDocumentPut201JSONResponse) VisitIndexDocumentPutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type IndexDocumentPut400JSONResponse ErrorResponse

func (response IndexDocumentPut400JSONResponse) VisitIndexDocumentPutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type IndexDocumentPut404JSONResponse ErrorResponse

func (response IndexDocumentPut404JSONResponse) VisitIndexDocumentPutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type RefreshRequestObject struct {
	Index IndexName `json:"index"`
}

type RefreshResponseObject interface {
	VisitRefreshResponse(w http.ResponseWriter) error
}

type Refresh200JSONResponse RefreshResponse

func (response Refresh200JSONResponse) VisitRefreshResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Refresh404JSONResponse ErrorResponse

func (response Refresh404JSONResponse) VisitRefreshResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type SearchGetRequestObject struct {
	Index  IndexName `json:"index"`
	Params SearchGetParams
	Body   *SearchGetJSONRequestBody
}

type SearchGetResponseObject interface {
	VisitSearchGetResponse(w http.ResponseWriter) error
}

type SearchGet200JSONResponse SearchResponse

func (response SearchGet200JSONResponse) VisitSearchGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SearchGet400JSONResponse ErrorResponse

func (response SearchGet400JSONResponse) VisitSearchGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type SearchGet404JSONResponse ErrorResponse

func (response SearchGet404JSONResponse) VisitSearchGetResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type SearchPostRequestObject struct {
	Index  IndexName `json:"index"`
	Params SearchPostParams
	Body   *SearchPostJSONRequestBody
}

type SearchPostResponseObject interface {
	VisitSearchPostResponse(w http.ResponseWriter) error
}

type SearchPost200JSONResponse SearchResponse

func (response SearchPost200JSONResponse) VisitSearchPostResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SearchPost400JSONResponse ErrorResponse

func (response SearchPost400JSONResponse) VisitSearchPostResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type SearchPost404JSONResponse ErrorResponse

func (response SearchPost404JSONResponse) VisitSearchPostResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Bulk operations
	// (POST /_bulk)
	Bulk(ctx context.Context, request BulkRequestObject) (BulkResponseObject, error)
	// Delete an index
	// (DELETE /{index})
	DeleteIndex(ctx context.Context, request DeleteIndexRequestObject) (DeleteIndexResponseObject, error)
	// Get index metadata
	// (GET /{index})
	GetIndex(ctx context.Context, request GetIndexRequestObject) (GetIndexResponseObject, error)
	// Create an index
	// (PUT /{index})
	CreateIndex(ctx context.Context, request CreateIndexRequestObject) (CreateIndexResponseObject, error)
	// Bulk operations with index scope
	// (POST /{index}/_bulk)
	BulkWithIndex(ctx context.Context, request BulkWithIndexRequestObject) (BulkWithIndexResponseObject, error)
	// Delete a document
	// (DELETE /{index}/_doc/{id})
	DeleteDocument(ctx context.Context, request DeleteDocumentRequestObject) (DeleteDocumentResponseObject, error)
	// Get a document
	// (GET /{index}/_doc/{id})
	GetDocument(ctx context.Context, request GetDocumentRequestObject) (GetDocumentResponseObject, error)
	// Index a document (POST)
	// (POST /{index}/_doc/{id})
	IndexDocumentPost(ctx context.Context, request IndexDocumentPostRequestObject) (IndexDocumentPostResponseObject, error)
	// Index a document (PUT)
	// (PUT /{index}/_doc/{id})
	IndexDocumentPut(ctx context.Context, request IndexDocumentPutRequestObject) (IndexDocumentPutResponseObject, error)
	// Refresh an index
	// (POST /{index}/_refresh)
	Refresh(ctx context.Context, request RefreshRequestObject) (RefreshResponseObject, error)
	// Search documents (GET)
	// (GET /{index}/_search)
	SearchGet(ctx context.Context, request SearchGetRequestObject) (SearchGetResponseObject, error)
	// Search documents (POST)
	// (POST /{index}/_search)
	SearchPost(ctx context.Context, request SearchPostRequestObject) (SearchPostResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// Bulk operation middleware
func (sh *strictHandler) Bulk(w http.ResponseWriter, r *http.Request) {
	var request BulkRequestObject

	request.Body = r.Body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Bulk(ctx, request.(BulkRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Bulk")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(BulkResponseObject); ok {
		if err := validResponse.VisitBulkResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteIndex operation middleware
func (sh *strictHandler) DeleteIndex(w http.ResponseWriter, r *http.Request, index IndexName) {
	var request DeleteIndexRequestObject

	request.Index = index

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteIndex(ctx, request.(DeleteIndexRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteIndex")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteIndexResponseObject); ok {
		if err := validResponse.VisitDeleteIndexResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetIndex operation middleware
func (sh *strictHandler) GetIndex(w http.ResponseWriter, r *http.Request, index IndexName) {
	var request GetIndexRequestObject

	request.Index = index

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetIndex(ctx, request.(GetIndexRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetIndex")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetIndexResponseObject); ok {
		if err := validResponse.VisitGetIndexResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateIndex operation middleware
func (sh *strictHandler) CreateIndex(w http.ResponseWriter, r *http.Request, index IndexName) {
	var request CreateIndexRequestObject

	request.Index = index

	var body CreateIndexJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateIndex(ctx, request.(CreateIndexRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateIndex")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateIndexResponseObject); ok {
		if err := validResponse.VisitCreateIndexResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// BulkWithIndex operation middleware
func (sh *strictHandler) BulkWithIndex(w http.ResponseWriter, r *http.Request, index IndexName) {
	var request BulkWithIndexRequestObject

	request.Index = index

	request.Body = r.Body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.BulkWithIndex(ctx, request.(BulkWithIndexRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "BulkWithIndex")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(BulkWithIndexResponseObject); ok {
		if err := validResponse.VisitBulkWithIndexResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteDocument operation middleware
func (sh *strictHandler) DeleteDocument(w http.ResponseWriter, r *http.Request, index IndexName, id DocId) {
	var request DeleteDocumentRequestObject

	request.Index = index
	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteDocument(ctx, request.(DeleteDocumentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteDocument")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteDocumentResponseObject); ok {
		if err := validResponse.VisitDeleteDocumentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDocument operation middleware
func (sh *strictHandler) GetDocument(w http.ResponseWriter, r *http.Request, index IndexName, id DocId) {
	var request GetDocumentRequestObject

	request.Index = index
	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDocument(ctx, request.(GetDocumentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDocument")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDocumentResponseObject); ok {
		if err := validResponse.VisitGetDocumentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// IndexDocumentPost operation middleware
func (sh *strictHandler) IndexDocumentPost(w http.ResponseWriter, r *http.Request, index IndexName, id DocId) {
	var request IndexDocumentPostRequestObject

	request.Index = index
	request.Id = id

	var body IndexDocumentPostJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.IndexDocumentPost(ctx, request.(IndexDocumentPostRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "IndexDocumentPost")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(IndexDocumentPostResponseObject); ok {
		if err := validResponse.VisitIndexDocumentPostResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// IndexDocumentPut operation middleware
func (sh *strictHandler) IndexDocumentPut(w http.ResponseWriter, r *http.Request, index IndexName, id DocId) {
	var request IndexDocumentPutRequestObject

	request.Index = index
	request.Id = id

	var body IndexDocumentPutJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.IndexDocumentPut(ctx, request.(IndexDocumentPutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "IndexDocumentPut")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(IndexDocumentPutResponseObject); ok {
		if err := validResponse.VisitIndexDocumentPutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Refresh operation middleware
func (sh *strictHandler) Refresh(w http.ResponseWriter, r *http.Request, index IndexName) {
	var request RefreshRequestObject

	request.Index = index

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Refresh(ctx, request.(RefreshRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Refresh")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RefreshResponseObject); ok {
		if err := validResponse.VisitRefreshResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SearchGet operation middleware
func (sh *strictHandler) SearchGet(w http.ResponseWriter, r *http.Request, index IndexName, params SearchGetParams) {
	var request SearchGetRequestObject

	request.Index = index
	request.Params = params

	var body SearchGetJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SearchGet(ctx, request.(SearchGetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchGet")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SearchGetResponseObject); ok {
		if err := validResponse.VisitSearchGetResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SearchPost operation middleware
func (sh *strictHandler) SearchPost(w http.ResponseWriter, r *http.Request, index IndexName, params SearchPostParams) {
	var request SearchPostRequestObject

	request.Index = index
	request.Params = params

	var body SearchPostJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SearchPost(ctx, request.(SearchPostRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchPost")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SearchPostResponseObject); ok {
		if err := validResponse.VisitSearchPostResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaTXPbNhP+Kxy8OeTt0Jbc5FLdktpVNVO3HtudHjyqBiJXEmISoAEwtuzhf+/ggyIp",
	"ghStmI7a8SkWucB+PA92F8s8oYDFCaNApUCjJ5RgjmOQwPWvUxZMQvUHoWiEEixXyEcUx4BGiITIRxzu",
	"UsIhRCPJU/CRCFYQY7UiJvQ3oEu5QqMTH8l1otYIyQldoizz0YSG8PC73sq9vXrfqiHBUgJXK/++wUeP",
	"w6Ofpvbf49nR9Id3yKX2ijzChfJxo/YuBb4u9AryCKisxu5BqIQlcJSpXcxbHaJPwS1l9xGESwgvQSSM",
	"Cu1SwlkCXBLQUrgkVdp0zlgEmGrLCkdvquLTjR9s/gUCiTIffU6j24mEuKwRhyGRhFEcXVR0v+OwQCP0",
	"v0GB9MA6MCjtk0Z65zZVSqTm2oyUPcpD7aOZQdD1CjhnfJdpZ0roFCQmkVojJJapcAJSjd0sZ85MM9Su",
	"awpiM2TaSOECy0dEQqxfbf7oGGSjqwgz5hyv9W/Gbjs4p8X83LbcEJdzP3PAEvQpu4S7FIQDuhgnCaHL",
	"nQ6c53IKB5Cyy5qrXC7Ldlm376HxURPF2o5TvsoVtFOIQMIpC9IYqGy2bA/O883xabd1i752mdNYa+Zn",
	"Fq6bz7/JmrXF5dNVc48DFow63TAPdjmh3/r5PtMm/TsOX18Zwmzemhp+IRCF19ZXoGmsvYIHiXx0C+t7",
	"xhU4EaNL5KOQpfNI+Zszc+rXAzcG2QuvZoKlPIBnE2DBUtqlFG3x0SxzhWwMsnae9ylJepNzkDjEEjsr",
	"kpb4lxzSqjcHlIHPS5qrNiWdoSqB6tRRBX0fMljJ9SksCNWrUYuisli9mlAcrR+Bt6a1NluKnOBMdy70",
	"L2HBQaxaOCpWmIe7oVRSVxJLUaei3cGl/gowD1a/EvlCmSZgvJz8aRrPVXrdNwm1HyqrrtUvB19X9mmn",
	"zqwIkKMli/FD4TJNowirLF91pQiBZBJH3fRda9F6a6ee+saBZq8bmzlzj3luGdDXHXfJbDSgicx56DtF",
	"XDy/690Rmescge1mJsJ5Rqhx+iuOUuhggZHzi83cZhSJuWqDocmMLWYckogE2Nmm+CW5Ii90QqbIDzXd",
	"C0yiSv9c0ifSIAAhFmnkfr8h9U6ADHdL+/m54nqkMt25L5jaOAQRcJIYgNBZhIUkgdB4Hin6YEnmEXjm",
	"iQd0SSh4ny4m6nJPpDqPaMwM/vbxV+DC7DY8PjkeKjdYAhQnBI3Qh+Ph8Qfk61mDjs5gNk8jzcGEmVOl",
	"YqcxnoRopO+IdgoBYtNqB4xKoFocJxpQtWDwcETDL7Zzrg0QNq1Etj3UMI2HPlTaph+HwxYldQW77p7F",
	"vVPprkZcvfd46WL68QWVV5t8l3Yceja0mlMijWOsspixawOFKXuDJ10hMsMbdVOr42VucBNbScrTrBu3",
	"rYXIoBhJZdMeIXFOjBzB0eZ4xtHQQPPx9aAx2imTnmn5q/CYMHuYeqZoZz5aguP45JeCQ8WidmlpjERc",
	"upEcEBBjkAaCioFJ6sCiNHP5Zji6ZMPnxcExr8psruwJe9cMqjH+gRYODyhDGvNLR7CUIbtUtb+IXL0e",
	"Gd5KY1+l0bsncmVzgAiYvZ4WTAhZMHgiYYeqmY9UvoUQ/k5h802p16zeMMZ1RDmX6avM7mHJrpLrhTlM",
	"LUX3PwOla2zaFj0buZdF8blGtBXrKn7u9FwZcF4okVeD8eULe+UzRacUf/Jiut2T4jbovledP8dJAtxL",
	"MBeELj3zieKwWk3ztuCv9/7ij6vr/zf2m1UWp28kfiPxQZL4T8XhSsvEzdi+uX+2c/1DvdVuf3ZwRMmK",
	"eKWJ3WEBlRvYcL8xA0Flg7MFMhPBMfScdIr/TdRX4qkO/Xu+EW8N+B2Y2Umr+eApvu+l6KDoagOTpxXh",
	"vR+f2drozCBGvv/e7o2hbwxtYqht37Is+ycAAP//SH4cLQYqAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
